# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-case-conflict

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.14
      hooks:
        - id: ruff
        - id: ruff-format

    - repo: https://github.com/jendrikseipp/vulture
      rev: v2.7
      hooks:
          - id: vulture

    - repo: https://github.com/myint/eradicate
      rev: 2.2.0
      hooks:
          - id: eradicate

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.3.0
      hooks:
          - id: mypy
            args: [--check-untyped-defs]
            language: system
            exclude: ^.vulture_whitelist.py

    - repo: https://github.com/dosisod/refurb
      rev: v1.16.0
      hooks:
          - id: refurb
            language_version: python3.11
