site_name: data_check
nav:
    - Home: index.md
    - Installation: install.md
    - Databases: databases.md
    - Usage: usage.md
    - CSV checks: csv_checks.md
    - Loading data: loading_data.md
    - Running SQL: sql.md
    - Pipelines: pipelines.md
    - Test data: test_data.md
    - HowTos: howtos.md
    - Examples: example.md
    - Development: development.md

theme:
    name: readthedocs
