site_name: data_check
nav:
    - Home: index.md
    - Installation: install.md
    - Usage: usage.md
    - CSV checks: csv_checks.md
    - Pipelines: pipelines.md
    - Test data: test_data.md
    - HowTos: howtos.md
    - Examples: example.md
    - Development: development.md
