version: "3.3"
services:
    data_check:
      build:
        context: ../../
        dockerfile: int_test/oracle/Dockerfile
    db:
        image: oracle/database:18.4.0-xe
        shm_size: '1gb'
        environment:
          - ORACLE_PWD=data_check

